// <auto-generated />
using System;
using Hotel_System.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hotel_System.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240829172422_required realtion")]
    partial class requiredrealtion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hotel_System.Core.Domain.Entites.Villa", b =>
                {
                    b.Property<Guid>("VillaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("VARCHAR(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VillaDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VillaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VillaID");

                    b.ToTable("Villas", (string)null);

                    b.HasData(
                        new
                        {
                            VillaID = new Guid("9b53e271-19fd-4b84-a14c-598e536ea22c"),
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 8, 29, 17, 24, 22, 371, DateTimeKind.Utc).AddTicks(3974),
                            ImageURL = "https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa3.jpg",
                            Occupancy = 4,
                            Rate = 200.0,
                            Sqft = 550,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaDescription = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            VillaName = "Royal Villa"
                        },
                        new
                        {
                            VillaID = new Guid("bcfad10a-d4fc-44f1-b5b1-0f5aa2c66147"),
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 8, 29, 17, 24, 22, 371, DateTimeKind.Utc).AddTicks(3989),
                            ImageURL = "https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa1.jpg",
                            Occupancy = 4,
                            Rate = 300.0,
                            Sqft = 550,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaDescription = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            VillaName = "Premium Pool Villa"
                        },
                        new
                        {
                            VillaID = new Guid("aef0a7d2-1e79-4bdf-8d3e-b46de9f8656e"),
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 8, 29, 17, 24, 22, 371, DateTimeKind.Utc).AddTicks(3992),
                            ImageURL = "https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa4.jpg",
                            Occupancy = 4,
                            Rate = 400.0,
                            Sqft = 750,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaDescription = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            VillaName = "Luxury Pool Villa"
                        },
                        new
                        {
                            VillaID = new Guid("6e6fe821-13d2-4567-b674-f616d79e264a"),
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 8, 29, 17, 24, 22, 371, DateTimeKind.Utc).AddTicks(3995),
                            ImageURL = "https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa5.jpg",
                            Occupancy = 4,
                            Rate = 550.0,
                            Sqft = 900,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaDescription = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            VillaName = "Diamond Villa"
                        },
                        new
                        {
                            VillaID = new Guid("02454e31-1236-4b7b-805f-7ecec9856090"),
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 8, 29, 17, 24, 22, 371, DateTimeKind.Utc).AddTicks(3998),
                            ImageURL = "https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa2.jpg",
                            Occupancy = 4,
                            Rate = 600.0,
                            Sqft = 1100,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaDescription = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            VillaName = "Diamond Pool Villa"
                        });
                });

            modelBuilder.Entity("Hotel_System.Core.Domain.Entites.VillaNumber", b =>
                {
                    b.Property<int>("VillaNum")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VillaID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VillaNum");

                    b.HasIndex("VillaID");

                    b.ToTable("VillaNumbers");
                });

            modelBuilder.Entity("Hotel_System.Core.Domain.Entites.VillaNumber", b =>
                {
                    b.HasOne("Hotel_System.Core.Domain.Entites.Villa", "Villa")
                        .WithMany("VillaNumbers")
                        .HasForeignKey("VillaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });

            modelBuilder.Entity("Hotel_System.Core.Domain.Entites.Villa", b =>
                {
                    b.Navigation("VillaNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
